"""update foreign key in friendship status

Revision ID: 10b24a318e56
Revises: 7853f5e7004f
Create Date: 2022-11-06 20:46:23.446349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b24a318e56'
down_revision = '7853f5e7004f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('friendship_status_addressee_id_FK', table_name='friendship_status')
    op.drop_constraint('friendship_status_status_code_id_FK', 'friendship_status', type_='foreignkey')
    op.create_foreign_key('friendship_status_status_code_id_FK', 'friendship_status', 'friendship_status_code', ['status_code_id'], ['status_code_id'], onupdate='CASCADE', ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendship_status_status_code_id_FK', 'friendship_status', type_='foreignkey')
    op.create_foreign_key('friendship_status_status_code_id_FK', 'friendship_status', 'friendship_status_code', ['status_code_id'], ['status_code_id'])
    op.create_index('friendship_status_addressee_id_FK', 'friendship_status', ['addressee_id'], unique=False)
    # ### end Alembic commands ###
