"""setup first tables

Revision ID: 2cd8c3fa9311
Revises: 905b51c79868
Create Date: 2022-10-29 17:34:16.677428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd8c3fa9311'
down_revision = '905b51c79868'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship_status_code',
    sa.Column('status_code_id', sa.CHAR(length=1), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('status_code_id', 'name'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('status_code_id')
    )
    op.create_table('group_chat',
    sa.Column('group_chat_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('group_chat_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=25), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('birthdate', sa.DATETIME(), nullable=True),
    sa.Column('password_hash', sa.CHAR(length=60), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friendship',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('created_date_time', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['user.user_id'], name='friendship_addressee_id_FK', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['user.user_id'], name='friendship_requester_id_FK', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('requester_id', 'addressee_id')
    )
    op.create_table('group_chat_member',
    sa.Column('group_chat_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chat.group_chat_id'], name='group_chat_member_group_chat_id_FK', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['user.user_id'], name='group_chat_member_member_id_FK', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_chat_id', 'member_id')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('reciever_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=300), nullable=False),
    sa.Column('created_date_time', sa.DATETIME(), nullable=False),
    sa.Column('last_edited_date_time', sa.DATETIME(), nullable=True),
    sa.Column('group_chat_id', sa.Integer(), nullable=True),
    sa.Column('seen', sa.BOOLEAN(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['group_chat_id'], ['group_chat.group_chat_id'], name='message_group_chat_id_FK', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reciever_id'], ['user.user_id'], name='message_reciever_id_FK', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.user_id'], name='message_sender_id_FK', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('friendship_status',
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('specified_date_time', sa.DATETIME(), nullable=False),
    sa.Column('status_code_id', sa.CHAR(length=1), server_default='R', nullable=False),
    sa.Column('specifierId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['friendship.addressee_id'], name='friendship_status_addressee_id_FK', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['friendship.requester_id'], name='friendship_status_requester_id_FK', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specifierId'], ['user.user_id'], name='friendship_status_specifier_id_FK', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_code_id'], ['friendship_status_code.status_code_id'], name='friendship_status_status_code_id_FK', onupdate='CASCADE', ondelete='SET DEFAULT'),
    sa.PrimaryKeyConstraint('requester_id', 'addressee_id', 'specified_date_time')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship_status')
    op.drop_table('message')
    op.drop_table('group_chat_member')
    op.drop_table('friendship')
    op.drop_table('user')
    op.drop_table('group_chat')
    op.drop_table('friendship_status_code')
    # ### end Alembic commands ###
