"""change individual foreign keys in FriendshipStatusSchema to a composite foreign key relating to FriendshipSchema

Revision ID: 618a9abaab80
Revises: b186bd31c6f7
Create Date: 2022-11-02 13:43:23.559821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618a9abaab80'
down_revision = 'b186bd31c6f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendship_status_requester_id_FK', 'friendship_status', type_='foreignkey')
    op.drop_constraint('friendship_status_status_code_id_FK', 'friendship_status', type_='foreignkey')
    op.drop_constraint('friendship_status_addressee_id_FK', 'friendship_status', type_='foreignkey')
    op.create_foreign_key('friendship_status_status_code_id_FK', 'friendship_status', 'friendship_status_code', ['status_code_id'], ['status_code_id'], onupdate='CASCADE', ondelete='SET DEFAULT')
    op.create_foreign_key('friendship_status_friend_id_FK', 'friendship_status', 'friendship', ['requester_id', 'addressee_id'], ['requester_id', 'addressee_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendship_status_friend_id_FK', 'friendship_status', type_='foreignkey')
    op.drop_constraint('friendship_status_status_code_id_FK', 'friendship_status', type_='foreignkey')
    op.create_foreign_key('friendship_status_addressee_id_FK', 'friendship_status', 'friendship', ['addressee_id'], ['addressee_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('friendship_status_status_code_id_FK', 'friendship_status', 'friendship_status_code', ['status_code_id'], ['status_code_id'])
    op.create_foreign_key('friendship_status_requester_id_FK', 'friendship_status', 'friendship', ['requester_id'], ['requester_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
