"""add onupdate and ondelete to status_code_id foreign key

Revision ID: b186bd31c6f7
Revises: f190687a3407
Create Date: 2022-11-02 13:03:25.533404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b186bd31c6f7'
down_revision = 'f190687a3407'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendship_status_status_code_id_FK', 'friendship_status', type_='foreignkey')
    op.create_foreign_key('friendship_status_status_code_id_FK', 'friendship_status', 'friendship_status_code', ['status_code_id'], ['status_code_id'], onupdate='CASCADE', ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('friendship_status_status_code_id_FK', 'friendship_status', type_='foreignkey')
    op.create_foreign_key('friendship_status_status_code_id_FK', 'friendship_status', 'friendship_status_code', ['status_code_id'], ['status_code_id'])
    # ### end Alembic commands ###
